In [1]:
import requests
import pandas as pd
import json

In [2]:
userjs = requests.get('http://jsonplaceholder.typicode.com/users')
user = userjs.json()

In [3]:
salarydata=[]
salary = pd.read_json('D:\Vito\Work Prep\CADIT\salary_data.json')
for i in range(10):
    userid = salary['array'][i]['id']
    usersalary = salary['array'][i]['salaryInIDR']
    salarydata.append([userid, usersalary])
salarytable = pd.DataFrame(salarydata)
salarytable.columns = ['id','salaryIDR']

In [4]:
userdata = []
for i in range(10):
    id = user[i]['id']
    name = user[i]['name']
    uname = user[i]['username']
    email = user[i]['email']
    address = str(user[i]['address']['street'])+", "+str(user[i]['address']['suite'])+", "+str(user[i]['address']['city'])+", "+str(user[i]['address']['zipcode'])+", "+str(user[i]['address']['geo'])
    phone =  user[i]['phone']
    userdata.append([id, name, uname, email, address, phone])
usertable = pd.DataFrame(userdata)
usertable.columns = ['id','name', 'username', 'email', 'address', 'phone']

In [5]:
userslry = pd.merge(usertable, salarytable, on='id')
userslry

,id,name,username,email,address,phone,salaryIDR
0,1,Leanne Graham,Bret,Sincere@april.biz,"Kulas Light, Apt. 556, Gwenborough, 92998-3874...",1-770-736-8031 x56442,4.001112e+06
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"Victor Plains, Suite 879, Wisokyburgh, 90566-7...",010-692-6593 x09125,4.685534e+06
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"Douglas Extension, Suite 847, McKenziehaven, 5...",1-463-123-4447,3.013602e+06
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"Hoeger Mall, Apt. 692, South Elvis, 53919-4257...",493-170-9623 x156,9.619331e+06
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"Skiles Walks, Suite 351, Roscoeview, 33263, {'...",(254)954-1289,8.380697e+06
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"Norberto Crossing, Apt. 950, South Christy, 23...",1-477-935-8478 x6430,9.091825e+06
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"Rex Trail, Suite 280, Howemouth, 58804-1099, {...",210.067.6132,6.996573e+06
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"Ellsworth Summit, Suite 729, Aliyaview, 45169,...",586.493.6943 x140,3.910255e+06
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"Dayna Park, Suite 449, Bartholomebury, 76495-3...",(775)976-6794 x41206,5.968429e+06
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"Kattie Turnpike, Suite 198, Lebsackbury, 31428...",024-648-3804,5.964808e+06

In [6]:
convert = requests.get('https://free.currconv.com/api/v7/convert?apiKey=f3b2235e37e079dd4905&q=IDR_USD&compact=y').json()
convIDR = convert['IDR_USD']['val']

In [8]:
usd = pd.DataFrame(userslry['salaryIDR']*convIDR)
usd.columns = ['salaryUSD']
output = pd.concat([userslry,usd], axis = 1)
#usertable.columns = ['id','USD']
#userslry = pd.merge(userslry, usd, on='id')

In [9]:
output

,id,name,username,email,address,phone,salaryIDR,salaryUSD
0,1,Leanne Graham,Bret,Sincere@april.biz,"Kulas Light, Apt. 556, Gwenborough, 92998-3874...",1-770-736-8031 x56442,4.001112e+06,285.139896
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"Victor Plains, Suite 879, Wisokyburgh, 90566-7...",010-692-6593 x09125,4.685534e+06,333.915408
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"Douglas Extension, Suite 847, McKenziehaven, 5...",1-463-123-4447,3.013602e+06,214.764835
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"Hoeger Mall, Apt. 692, South Elvis, 53919-4257...",493-170-9623 x156,9.619331e+06,685.523299
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"Skiles Walks, Suite 351, Roscoeview, 33263, {'...",(254)954-1289,8.380697e+06,597.251769
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"Norberto Crossing, Apt. 950, South Christy, 23...",1-477-935-8478 x6430,9.091825e+06,647.930432
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"Rex Trail, Suite 280, Howemouth, 58804-1099, {...",210.067.6132,6.996573e+06,498.611983
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"Ellsworth Summit, Suite 729, Aliyaview, 45169,...",586.493.6943 x140,3.910255e+06,278.664986
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"Dayna Park, Suite 449, Bartholomebury, 76495-3...",(775)976-6794 x41206,5.968429e+06,425.341134
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"Kattie Turnpike, Suite 198, Lebsackbury, 31428...",024-648-3804,5.964808e+06,425.083082